---
title: "Week5 Assignment - Tyding & Transforming Data"
author: "humbertohp"
date: "September 27, 2018"
output:
  html_document:
    theme: cerulean
---

# Load data set (CSV) into R and load required libraries

```{r, echo=TRUE}

arrivals_raw <- data.frame(read.csv("https://raw.githubusercontent.com/humbertohpgit/MSDS1stSem/master/Arrival_Delays.csv", header = TRUE, stringsAsFactors=FALSE))
arrivals_raw
library(dplyr)
library(tidyr)
library(stringr)
```

# Data Wrangling
## Pivoting columns to rows and Renaming columns
```{r, echo=TRUE}
arrivals1 <- gather(arrivals_raw,"City", "Arrivals", 3:7)
names(arrivals1) <- c("Airline", "Type", "City", "Arrivals")
```

## Filtering Nulls/NAs
```{r, echo=TRUE}
arrivals2 <- filter(arrivals1, !is.na(Arrivals), Arrivals != "")
```

## Removing punctuation/spaces and Recasting data types
```{r, echo=TRUE}
arrivals2$Arrivals <- str_remove(arrivals2$Arrivals, ",")
arrivals2$Arrivals <- str_trim(arrivals2$Arrivals)
arrivals2$Arrivals <- as.numeric(arrivals2$Arrivals)
arrivals2$City <- str_replace_all(arrivals2$City, pattern = "\\.", replacement = " ")
```

## Fill in missing values
```{r, echo=TRUE}
arrivals2[arrivals2$Airline == "",1] <- NA
arrivals3 <- arrivals2 %>% fill(Airline)
```

## Final tidy data set
```{r, echo=TRUE}
tbl_df(arrivals3)
```

# Analysis comparing arrival delays for the two airlines
```{r, echo=TRUE}
library(ggplot2)
arrivals_chart <- summarise(group_by(arrivals3, Airline, Type), Arrivals = sum(Arrivals))
arrivals_chart
ggplot(arrivals_chart, aes(x=Type, y=Arrivals, fill = Airline)) + geom_col(position = "dodge") + labs(y = "Arrivals", x = "Type", title = "Arrival Delays") + theme_bw()  ##+ stat_identity()
```
                          
### Arrival delays for AM West are greater than Alaska by 286. 787 vs 501 respectively